# Setup
title:	Hammad Ahmad Usmani
tagline:	Computer Scientist & Machine Learning Engineer
baseurl:	""
paginate:	1

# About/contact
author: Hammad Ahmad Usmani

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-cayman
